spring:
  config:
    activate:
      on-profile: local
  kafka:
    template:
      default-topic: bookstore-events
    producer:
      bootstrap-servers: localhost:9092, localhost:9091, localhost:9093
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:9092, localhost:9091, localhost:9093

---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    template:
      default-topic: bookstore-events
    producer:
      bootstrap-servers: dev:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    template:
      default-topic: bookstore-events
    producer:
      bootstrap-servers: prod:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
